### PR TITLE
Add winget installation option

### PR DESCRIPTION
**Pull request by brl0**
Related to #512.

### CODE REVIEW

**Comment by krassowski** [comment]
Thanks! What do we need to do to keep the winget version up-to-date?

**Comment by brl0** [comment]
@krassowski,  That's a great question I had been looking into myself but not yet found a great answer for.

The package I originally added was actually for the pre-release of `3.5.1-1`, which thankfully @mdanish-kh noticed and has corrected this oversight.  

@mdanish-kh, do you have any suggestions on the best way to keep this up to date?  Are there any common CI integrations or scripting tools for automating this?

**Comment by brl0** [comment]
So the simplest answer is to submit a PR to add or update the yaml files in this repo:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/ProjectJupyter

**Comment by mdanish-kh** [comment]
The authors can set up a GitHub Action similar to the one setup in microsoft/Powertoys repo https://github.com/microsoft/PowerToys/actions/workflows/package-submissions.yml

There is also a community solution to publish packages easily to the winget repo https://github.com/vedantmgoyal2009/winget-releaser/. @vedantmgoyal2009 can help you with that one I'm sure.

**Review by mbektas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
