### PR TITLE
Snap support

### PR DESCRIPTION
**Pull request by mbektas**

### CODE REVIEW

**Comment by dmitry-lyfar** [comment]
> @dmitry-lyfar I think it would be fine if environments can be restored within 30 days and not affected by app updates.
> 
> 
> 
> now the snap uploads are failing because of classic confinement. is it something you can resolve on your end?

Yes, I’m awaiting the resolution here: 
https://forum.snapcraft.io/t/request-for-confinement-classic-for-jupyterlab-desktop/39047/4

Once approved, the upload will start to be working.

**Comment by dmitry-lyfar** [comment]
@mbektas the snap's classic confinement has been approved: https://forum.snapcraft.io/t/request-for-confinement-classic-for-jupyterlab-desktop/39047/5

Could you try if that works for you, please?

**Comment by mbektas** [comment]
thanks @dmitry-lyfar . I will trigger a publish now.

**Comment by mbektas** [comment]
@dmitry-lyfar build is succeeding now and snap is uploaded properly. I would like to test the cycle of install -> uninstall -> reinstall -> update.

**Comment by mbektas** [comment]
@dmitry-lyfar I will go ahead and merge your changes. thanks for your contribution. `jlab` CLI is not working with the snap but there might be a way to solve using snap hooks support with electron builder. we can follow up on that on another PR. we need to add CLI support before we can publicly announce snap support.

**Comment by mbektas** [comment]
Also, I plan to manually promote from candidate to stable for now.

**Pull request merged**
