### PR TITLE
Rewrite, with Welcome Page and session history

### PR DESCRIPTION
**Pull request by mbektas**
desktop new 2

- Sessions
  - There are two types of sessions: local and remote
  - Local session: Working Directory, files to open (optional)
  - Remote session: Server URL, persistSessionData flag
  - Sessions can be closed and new ones can be created without closing desktop app
  - close-session

- Welcome Page
  - welcome-page
  - Links to create new notebook, launch new JupyterLab session, open files / folders in new session, connect to existing local / remote JupyterLab servers
  - Recent session list with ability to relaunch
  - News on Welcome Page. Using Jupyter Blog feed. Clicking opens in external browser. News are cached, updated at every app launch.
  - Drag and Drop files / folder to open in a new session

-  First Launch Screen
  - first-screen

- Configuration Changes
  - jupyterlab-desktop-data file removed
  - [USER-DATA-DIR]/app-data.json stores application data and cache (sessions, recent items, news)
  - [USER-DATA-DIR]/settings.json stores user defaults
  - [WORKING-DIRECTORY]/.jupyter/desktop-settings.json (workspace settings) overrides user defaults (e.g. Python path)
  - [WORKING-DIRECTORY]/.jupyter/desktop-workspaces stores workspaces for the working directory
  - Default Working Directory can be set
  - Default Python environment can be set
  - Prettified JSON config files
  -  preferences-server
  - preferences-privacy

- CLI Changes
  - Specify working directory or Python path to use
  - Open multiple files
  - `jlab --help` with examples

- Connect to existing JupyterLab Server
  - connect-to-existing
  - Recent connections and locally running JupyterLab servers listed. user can enter new URLs

- Registry
  - Local Python environments are discovered at launch
  - Local JupyterLab servers running are discovered

- Server Status on title bar
  - Remote server status is not clickable anymore. User is expected to close session and connect to new server
  - Local server status clicks shows list of Python environments and allows browsing / specifying a Python path. Selecting new Python env relaunches JupyterLab at the same working directory without relaunching desktop app
  - env-selection

- Startup Mode
  - preferences-general
  - Three modes: Show Welcome Page, Start New Session (old behavior), Restore Last Session

- Progress View
  - progress-view
  - Shown during time consuming tasks such as new server launch and also when errors occur
  - Has subtle animation around JupyterLab icon
  - Progress messages shown on view with a title and message lines. They can be in HTML format. Provides `sendMessageToMain` method to enable action links

- Architectural Changes
  - Major refactoring and rewrite of the code-base
  - Simplification and clean-up
  - Changes towards support for multiple windows/sessions

Tasks
- [x] Architectural redesign 
- [x] Separate app state and settings. Introduce workspace (working directory) settings
- [x] Welcome Page
- [x] Open notebook / folder from UI
- [x] Recent session list and ability to reopen
- [x] News feed from Jupyter Blog
- [x] Close session and open new without relaunch
- [x] Default Python env and working directory in Preferences dialog. Default working directory now configurable in UI
- [x] Remote server URL history and autocomplete in UI
- [x] User configurable startup modes: Welcome Page, New Local Session, Restore Last Session
- [x] Cleaner, prettified JSON config files
- [x] Drag - drop support on Welcome Page
- [x] CLI with pythonPath and working directory options
- [x] List and connect to existing local servers
- [x] More user friendly Python env selection on UI using popup. New env applied without app restart. Existing environments are discovered and listed as options
- [x] Progress view and better server launch error handling
- [x] Check for bundled environment updates and update in Preferences dialog
- [x] Refactor session create methods
- [x] Refactoring, cleanup
- [x] Testing

### CODE REVIEW

**Comment by mbektas** [comment]
Code is not ready for merge yet but the changes are ready for UI/UX/feature review and testing. cc'ing @ellisonbg, @blink1073, @jasongrout for awareness and any feedback.

**Comment by mbektas** [comment]
> Very nice! I did find it a bit confusing where a localhost address was considered "remote", but I suppose if you had explicitly listed it as such it would make sense.

Thanks @blink1073 . That is a good point and one of things I had trouble naming.
- Remote: covers both local URLs and remote URLs connected
- Local: local servers launched by the app

I will be happy to rename to if we can find better names. It is open for suggestions. Some options could be:
For title bar status
- instead of `Local: (env_type: env_name)`: `Server: (env_type: env_name)`
- instead of `Remote`: `Local connection` / `Remote connection` based on URL or just `Local` / `Remote`

For recents list, instead of [`URL` `remote`]
- [`URL` `local` / `remote`] 
- or just [`URL`] since local / remote is obvious

**Comment by blink1073** [comment]
Maybe "internal" vs "external" for who is running the server?

**Comment by krassowski** [comment]
I see a blank window on Ubuntu:

image

with logs

```
[2023-01-15 15:54:26.818] [error] Failed to create free server Error: No default environment found!
    at /opt/JupyterLab/resources/app.asar/build/out/main/registry.js:176:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-01-15 15:56:31.164] [error] (node:311152) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'protocol')
    at new LabView (/opt/JupyterLab/resources/app.asar/build/out/main/labview/labview.js:59:50)
    at MainWindow._loadLabView (/opt/JupyterLab/resources/app.asar/build/out/main/mainwindow/mainwindow.js:240:25)
    at MainWindow._updateContentView (/opt/JupyterLab/resources/app.asar/build/out/main/mainwindow/mainwindow.js:603:18)
    at loadLabView (/opt/JupyterLab/resources/app.asar/build/out/main/mainwindow/mainwindow.js:342:22)
    at IpcMainImpl.<anonymous> (/opt/JupyterLab/resources/app.asar/build/out/main/mainwindow/mainwindow.js:366:13)
(Use `jupyterlab-desktop --trace-warnings ...` to show where the warning was created)
[2023-01-15 15:56:31.164] [error] (node:311152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2023-01-15 15:57:48.523] [info]  In production mode
[2023-01-15 15:57:48.526] [info]  Logging to file (~/.config/jupyterlab-desktop/logs/main.log) at 'debug' level
[2023-01-15 15:57:52.249] [error] Failed to create free server Error: No default environment found!
    at /opt/JupyterLab/resources/app.asar/build/out/main/registry.js:176:32
```

I can close session but then clicking on new session or new notebook results in:

image

I am confident that my custom Python environment is correct and includes required dependencies.

**Comment by mbektas** [comment]
@krassowski are you on `Client-app mode`? that is currently broken. If you have a custom environment set in previous version that won't be carried over, you need to set it again by clicking `Change the default Python environment`

**Comment by mbektas** [comment]
> Maybe "internal" vs "external" for who is running the server?

thanks @blink1073 . this is a good idea too. I updated the labeling yesterday but I will revisit. Now:
- title bar shows:
  - for app launched servers: `Python env info` instead of `Local: (Python env info)`
  - for connected servers: `Local` for localhost, `Remote` for other URLs
- recents list shows just the URL on the left with no `remote` tag on right.

**Comment by blink1073** [comment]
^ That looks good to me actually

**Comment by krassowski** [comment]
I was running a version a few commits behind ([b6a2795](https://github.com/jupyterlab/jupyterlab-desktop/pull/546/commits/b6a27956c72638092996afa71fc87f379ed8f706)) for few days now and had overall good impressions. Some noticeable annoyances that I saw are:

1. When I start a new session from command line I see:
   Screenshot from 2023-01-25 20-26-51
   not sure if this is a me problem or a real bug
2. (major UX) When changing environment using file picker the path is set in the input but then nothing happens. To actually change it I need to focus the input and press enter. It is very un-intuitve as the only button is the folder which opens the file picker dialog again. I think it is sensible to accept the choice upon getting the path from file picker..
3. (annoyance) when I change environment the zoom level is not saved. When I use my very large monitor I have to hit ctrl + shift + plus several times each time which is annoying (also because of https://github.com/jupyterlab/jupyterlab-desktop/issues/550).
4. when I change virtual environment the notebooks that I had open do not get re-opened
5. (very minor) it would be a lovely addition if the scrollbar in the env picker was styled in dark mode, this is how it looks for me now:
    Screenshot from 2023-01-25 20-29-39

**Comment by krassowski** [comment]
I guess that point (4) was already fixed by [119da42](https://github.com/jupyterlab/jupyterlab-desktop/pull/546/commits/119da427348aa9efc35cf16bedc125fc04cfe336) but have not tested yet.

**Comment by krassowski** [comment]
Idea: one useful addition to the welcome screen could be a set of links to this repository ("Report a bug"/"Open a feature request"/"Contribute").

**Comment by mbektas** [comment]
@krassowski thanks for testing. (1) happens when you start another instance of the app. I am working on a fix for that. Regarding (2), there is tooltip with the requirement to hit 'Enter' but I will apply the selected path from file dialog as you suggest. I will look into (3). (4) is fixed in the latest as you guessed.  I would like to leave (5) for later. There are other scroll bars (recents list, connect to server list) which might have the same issue.

**Comment by mbektas** [comment]
> Idea: one useful addition to the welcome screen could be a set of links to this repository ("Report a bug"/"Open a feature request"/"Contribute").

I am not too sure about this, it would be better to keep welcome page simple and clean. We could add these links to about dialog.

**Comment by mbektas** [comment]
@krassowski I couldn't reproduce (3). it worked fine on macOS, Windows and Ubuntu for me. and I pushed fixes for (1) and (2).

**Comment by krassowski** [comment]
Some more comments:
- What do you think about adding "open welcome screen" item in the hamburger menu? currently one needs to close current session to get it I think.
- the environment picker/list does not close when clicking on title bar. It is a very minor but I do notice it sometimes.

**Comment by krassowski** [comment]
It seems that I no longer can open two sessions at once, I get this dialog

Screenshot from 2023-01-28 21-16-42

this prevents me from working on two projects simultaneously. This is a serious downgrade for me.

**Comment by mbektas** [comment]
> Some more comments:
> 
> * What do you think about adding "open welcome screen" item in the hamburger menu? currently one needs to close current session to get it I think.
> * the environment picker/list does not close when clicking on title bar. It is a very minor but I do notice it sometimes.

As you also mentioned in your next comment, currently only single session window is supported. I am planning to add multiple window support in the next release. but I will see if I can include in this PR. I am thinking of adding `New Window` menu item that opens welcome page in new window.

You can click on the jlab view or hit Escape to close to Python env list. but I will also make sure title bar clicks hide it as well.

**Comment by krassowski** [comment]
> I am planning to add multiple window support in the next release.

Just FYI, I will be staying with build prior to https://github.com/jupyterlab/jupyterlab-desktop/pull/546/commits/1b2b2a8c9a82fe3f8948e5eef00d7c6faa52282c and possibly apply patches locally as having multiple sessions is a critical feature for me.

> I am thinking of adding New Window menu item that opens welcome page in new window.

Sounds like a good idea. FYI, on Ubuntu for example when I click on the icon in the OS launcher it already has a "New Window" option and it already worked like that prior to 1b2b2a8c9a82fe3f8948e5eef00d7c6faa52282c:

Screenshot from 2023-01-29 01-42-04

**Comment by mbektas** [comment]
@krassowski  hiding the env select popup when titlebar is clicked turned out to be quite complex. It works on macOS but not on Linux / Windows. Since it is a window drag region, mouse events are not being received by the listeners.

I will try multiple window support in another PR but before releasing these changes. it will most likely be relatively easy thanks to this PR, but I have to try and see. This PR makes event handling specific to the SessionWindow, designed for the multiple windows.

By the way, I wouldn't stay before https://github.com/jupyterlab/jupyterlab-desktop/commit/1b2b2a8c9a82fe3f8948e5eef00d7c6faa52282c . Because multiple instances would modify the shared app-data.json and settings.json files which may cause issues.

**Pull request merged**
