### PR TITLE
Release v3.5.1-1

### PR DESCRIPTION
**Pull request by mbektas**
- UI remake and refactoring https://github.com/jupyterlab/jupyterlab-desktop/pull/513
- Web-app mode for JupyterLab UI https://github.com/jupyterlab/jupyterlab-desktop/pull/529
- Upgrade to electron 22 https://github.com/jupyterlab/jupyterlab-desktop/pull/526
- Proper server shutdown https://github.com/jupyterlab/jupyterlab-desktop/pull/528
- Update to JupyterLab 3.5.1 https://github.com/jupyterlab/jupyterlab-desktop/pull/530

New UI and dialogs
jupyterlab-desktop

local server

remote server

appearance

updates

about

### CODE REVIEW

**Review by krassowski — COMMENTED** [review]
Works ok-ish for me. I encountered a number of issues with the title bar and I am a bit annoyed by them. It would be perfect if we could fix at least some of them:
- https://github.com/jupyterlab/jupyterlab-desktop/issues/534
- https://github.com/jupyterlab/jupyterlab-desktop/issues/535
- https://github.com/jupyterlab/jupyterlab-desktop/issues/536
- https://github.com/jupyterlab/jupyterlab-desktop/issues/537
- https://github.com/jupyterlab/jupyterlab-desktop/issues/538
- https://github.com/jupyterlab/jupyterlab-desktop/issues/539

**Comment by krassowski** [comment]
Well apparently GitHub does not render issue lists in review comments, so here we go again:
- https://github.com/jupyterlab/jupyterlab-desktop/issues/534
- https://github.com/jupyterlab/jupyterlab-desktop/issues/535
- https://github.com/jupyterlab/jupyterlab-desktop/issues/536
- https://github.com/jupyterlab/jupyterlab-desktop/issues/537
- https://github.com/jupyterlab/jupyterlab-desktop/issues/538
- https://github.com/jupyterlab/jupyterlab-desktop/issues/539

**Comment by krassowski** [comment]
One more:
- #540

**Comment by mbektas** [comment]
@krassowski thanks for the review. I addressed the issues below.
- https://github.com/jupyterlab/jupyterlab-desktop/issues/534
- https://github.com/jupyterlab/jupyterlab-desktop/issues/535
- https://github.com/jupyterlab/jupyterlab-desktop/issues/536
- https://github.com/jupyterlab/jupyterlab-desktop/issues/538

I would like to leave the rest for after this release.

**Comment by krassowski** [comment]
Thank you!

**Pull request merged**
