### PR TITLE
Improve error handling on frontend & fix some floating promises

### PR DESCRIPTION
**Pull request by krassowski**
Builds on top of #487, enabling no-floating-promises rule and handling errors on frontend; should lead to more informative user reports for frontend issues (although these are not as common as server issues).

Also ensures that root path is available when opening files.

### CODE REVIEW

**Review by mbektas — APPROVED** [review]
LGTM. Thanks!

**Comment by mbektas** [comment]
@krassowski is this still in draft?

**Comment by krassowski** [comment]
I have some local work on sending server errors to frontend and there is a conflict to resolve. If you are thinking about cutting a release I would **not** wait for me to finish it as I may not have enough time this weekend.

**Comment by krassowski** [comment]
Closing as outdated.

**Pull request closed without merging**
