### PR TITLE
UI remake, refactoring

### PR DESCRIPTION
**Pull request by mbektas**
- [x] Decouple dialog windows from session
- [x] Theme support
- [x] Preferences Dialog for app-wide settings
- [x] Use [@jupyter-notebook/web-components](https://github.com/jupyterlab-contrib/jupyter-ui-toolkit/) for dialogs
- [x] About Dialog
- [x] Custom title bar
- [x] Security upgrade, introduce context isolation
- [x] Minimize JupyterLab customization (Help menu items etc.)
- [x] Properly apply Jupyter theme for @jupyter-notebook/web-components (FAST theme is applied currently)
- [x] Code refactoring & cleanup

## What is next
After this PR, below are the items I plan to work on. They should give more context on the changes in this PR.
- Multiple window (session) support. Each session is either local server launch with a specific working directory or remote server connection
- Root directory selection for local server launch
- Ability to change root directory
- LabView reload with new session, without app restart
- Welcome page: list of recent sessions to reopen quickly
- Browser mode (JupyterLab is opened in browser view (in LabView) instead of using bundled frontend) vs Client app mode (current bundled frontend)

## Screenshots of new UI
macOS UI
macOS UI

macOS App menu
macOS app menu

macOS Preferences Dialog - Appearance
macOS preferences new 1

macOS Preferences Dialog - Updates
macOS preferences new 2

macOS About Dialog
macOS about

macOS Server Config - Local
macOS local server new

macOS Server Config - Remote
macOS remote server new

macOS UI light
macOS UI light

macOS Preferences Dialog light
macOS preferences light new

Windows UI
windows app

### CODE REVIEW

**Comment by krassowski** [comment]
I tried it on Ubuntu and (1) could not open up a compatible virtual environment: the splash screen showed, then blank page froze and when I tried to open Dev Tools I saw "dev tools disconnected" message indicating a crash (so no. Then, when I installed a bundeled conda it loaded up correctly but I was unable to change the environment to the custom virtual environment and in a bit frustrating manner there was no feedback at all (I was clicking on the "Apply & restart" button but nothing was happening).

```
[2022-11-13 19:25:53.965] [error] Error occurred in handler for 'select-python-path': No handler registered for 'select-python-path'
[2022-11-13 19:25:54.145] [error] Error occurred in handler for 'select-python-path': No handler registered for 'select-python-path'
[2022-11-13 19:25:54.325] [error] Error occurred in handler for 'select-python-path': No handler registered for 'select-python-path'
[2022-11-13 19:31:18.209] [info]  In production mode
[2022-11-13 19:31:18.212] [info]  Logging to file (~/.config/jupyterlab-desktop/logs/main.log) at 'false' level
[2022-11-13 19:31:18.290] [error] (node:1846778) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `jupyterlab-desktop --trace-deprecation ...` to show where the warning was created)
[2022-11-13 19:31:20.888] [error] pyenv: conda: command not found

The `conda' command exists in these Python versions:
  3.7.5/envs/my-env-2
  my-env-2

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

[2022-11-13 19:31:20.889] [error] (node:1846778) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/JupyterLab/resources/app.asar/build/out/main/registry.js:629:34
[2022-11-13 19:31:20.889] [error] (node:1846778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by krassowski** [comment]
> Decouple dialog windows from session

:tada: :tada:

> Security upgrade, introduce context isolation

Thank you, this is amazing! :tada: :tada: :tada:

> Theme support

:tada:

> Custom title bar

Not a fan of apps customising my title bars in general (unless they do that without breaking native functionality, which is high-maintenance gamble that few apps achieve, although some do), but I'm fine with it being an option (whether opt-in or opt-out).

The usability of the new window is significantly reduced on Ubuntu/Gnome for me: resizing does not work on the top edge in the title area, I cannot access context menu options (see pic below what I expect) and it does not match the resolution or style of other windows. I much preferred having the statusbar item inside JupyterLab and a native window.

Screenshot from 2022-11-13 19-39-11

> Preferences Dialog for app-wide settings

I am on fence here: having these settings in the JupyterLab Settings editor is technically feasible (by adding a new extension with JSON schema and intercepting the contents), and could offer be a better UX. On the other hand it creates a clear distinction between core settings and Desktop settings.

**Comment by krassowski** [comment]
Could the custom title bar be an opt-in on Linux/Windows?

**Comment by krassowski** [comment]
Another issue with custom window/title bar: when maximised the JupyterLab content stays the same size as before maximising:

Screenshot from 2022-11-13 21-33-23

**Comment by mbektas** [comment]
@krassowski thanks for the review and testing. maximize issue and custom environment selection should be fixed now with my latest changes.

> Could the custom title bar be an opt-in on Linux/Windows?

yes we could possibly do that. but in that case we will need to show app menu and server status in context menu or similar. I would like to move away from customizing bundled JupyterLab or even bundling a front-end. It is creating restraints (e.g. frontend - backend version match requirement).

**Comment by mbektas** [comment]
> Could the custom title bar be an opt-in on Linux/Windows?

On Windows, electron actually shows system menu on right click on title bar (since it is a drag region).

**Pull request merged**
